// This would be in a file like `app/layout.tsx` or a server-side component file

import { Metadata } from "next";
import RootLayout from "./RootLayout"; // Import the client-side layout

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <RootLayout>
            {children}
        </RootLayout>
    );
}
